updates

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -13,6 +13,44 @@ jobs:
             - name: Checkout code
               uses: actions/checkout@v2
 
+            - name: Setup Go
+              uses: actions/setup-go@v2
+              with:
+                go-version: '1.15.8'
+
+            - name: Check go mod status
+              run: |
+                make gomod_tidy
+                if [[ ! -z $(git status -s) ]]
+                then
+                    echo "Go mod - state is not clean"
+                    git diff "$GITHUB_SHA"
+                    exit 1
+                fi
+
+            - name: Build Binary
+              run: make bin
+            - name: Check format
+              run: |
+                make gofmt
+                if [[ ! -z $(git status -s) ]]
+                then
+                    echo "go fmt - found badly formatted source : $(git status -s)"
+                    exit 1
+                fi
+
+            - name: Download dependencies
+              run: go mod download
+
+            - name: Run tests
+              run: |
+                  make test
+                  if [[ ! -z $(git status -s) ]]
+                  then
+                    echo "go test - errors running go tests : $(git status -s)"
+                    exit 1
+                  fi
+
             - name: Set up Python 3.x Part 1
               uses: actions/setup-python@v2
               with:
@@ -35,7 +73,7 @@ jobs:
               if: ${{ steps.check_version_in_PR.outputs.version_in_PR != ''}}
               uses: actions/checkout@v2
               with:
-                 ref: main
+                ref: main
 
             - name: Check if version updated
               id: check-version_updated
@@ -44,34 +82,21 @@ jobs:
                 # check if version file was changed
                 ve1/bin/version-checker --version=${{ steps.check_version_in_PR.outputs.version_in_PR }}
 
-            - name: Checkout code
-              if: ${{ steps.check-version_updated.outputs.updated != ''}}
-              uses: actions/checkout@v2
-
-            - name: Setup Go
-              uses: actions/setup-go@v2
-              with:
-                go-version: '1.15.8'
-
-            - name: Download dependencies
-              run: go mod download
-
-            - name: Run tests
-              run: make test
-
             - name: Build and Test Image
               id: build_and_test
               if: ${{ steps.check-version_updated.outputs.updated == 'true'}}
-              run: echo "Build and Test Image to be completed"
+                run: |
+                  ## build and test image
+                  ve1/bin/build-and-test ---image-name=${{steps.check_version_in_PR.outputs.PR_version_image}} -sha-value=${GITHUB_SHA}
 
-            - name: 'Approve PR'
+            - name: Approve PR
               id: approve_pr
-              if: ${{ steps.check-version_updated.outputs.updated == 'true' }}
+              if: ${{ steps.build_and_test.outputs.result == 'success' }}
               uses: hmarr/auto-approve-action@v2
               with:
                   github-token: ${{ secrets.GITHUB_TOKEN }}
 
-            - name: 'Merge PR'
+            - name: Merge PR
               id: merge_pr
               if: ${{ steps.approve_pr.conclusion == 'success' }}
               uses: pascalgn/automerge-action@v0.13.1
@@ -81,15 +106,9 @@ jobs:
                 MERGE_LABELS: ""
 
             - name: Check for PR merge
-              if: steps.check_ci_changes.outputs.run-tests != 'true'
+              if: ${{ steps.approve_pr.conclusion == 'success' }}
               run: |
                   ./ve1/bin/check-auto-merge --api-url=${{ github.event.pull_request._links.self.href }}
-
-            - name: Block until there is no running workflow
-              if: steps.check_ci_changes.outputs.run-tests != 'true'
-              uses: softprops/turnstyle@v1
-              env:
-                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
             - name: Create the the release
               id: create_release
